# _config.yml
url: https://matthiasrohr.github.io/securecoding
logo: 
avatar: 
title: Secure Coding Guidelines
description: Secure coding guidelines.
author: Matthias Rohr
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
repository: "matthiasrohr/securecoding"
enable_copy_code_button: true
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
search: true
  
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  #- jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/matthiasrohr"
  
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      comments: false
      sidebar: toc
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"


TITLE_GENERAL_REQUIREMENTS: "Types of Requirements"
URL_GENERAL_REQUIREMENTS: /General/Requirements

TITLE_GENERAL_TERMS: "Terms"
URL_GENERAL_TERMS: /General/Terms

TITLE_GENERAL_ROLES: "Roles"
URL_GENERAL_ROLES: /General/Roles

TITLE_GENERAL_RISKCLASSES: "Risk Classes"
URL_GENERAL_RISKCLASSES: /General/RiskClasses

TITLE_GENERAL_FAQ: "FAQ"
URL_GENERAL_FAQ: /General/FAQ

TITLE_GENERAL_LICENSE: "License"
URL_GENERAL_LICENSE: /licenses/by/4.0/deed.en

TITLE_SSDLC_CONTROLS: "Part A: SSDLC Controls"
URL_SSDLC_CONTROLS: /#part-a-ssdlc-controls

TITLE_SSDLC_SECENV: "A.1 - Secure Dev Environment"
URL_SSDLC_SECENV: /Controls/SSDLC_Secure-Dev-Environment

        
